version: '3.8'
services:
  auth-service:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - my-network
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://eureka:8761/eureka/

networks:
  my-network:
    driver: bridge